### ISSUE TITLE
ooo

### ISSUE THREAD

**Issue by chiragn888** [chiragn888/signup888#11]
the below is the modified code please use both and make it a proper single file 
do not use extra natural language and give full length code

***index.css***
```css
/* The rest of the css remains the same */

.input-field2:hover{
    zoom: 105%;
}
.button{
    width :80%;
    height: 37px;
    border-radius: 4px;
    font-size: 16px;
    border-style: none;
    background-image: linear-gradient(to right, #7f55ad, #3c96f5);
    color: white;
    margin-bottom: 15px;
    margin-top: 10px;
}
.button:hover{
   zoom: 105%;
    cursor: pointer;
}
#border{
    height: 500px;
    width: 400px;
    background-color: red;  /* Added background color red for border id */
}

/* The rest of the css remains the same */
```
